/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/3d/terem.glb 
Author: uvnik (https://sketchfab.com/uvnik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/terem-e215b6fd60ca48ddabaa77373f35176c
Title: TEREM
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import Tscene from "../assets/3d/terem.glb";

const Terem = (props) => {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF(Tscene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.003}>
          <group name="fba9153a7d32417e8254bf27e70aae45fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="����������������" position={[773.253, 16516.414, 464.291]}>
                  <group name="Polygon_0" position={[5568.262, -16641.215, 3288.798]} rotation={[2.343, -0.428, -1.806]} scale={1.109}>
                    <mesh name="Polygon_0_snejinka_0" geometry={nodes.Polygon_0_snejinka_0.geometry} material={materials.snejinka} />
                  </group>
                </group>
                <group name="������������" position={[1082.125, -298.323, 3298.035]} rotation={[0.646, 0.081, 1.611]}>
                  <mesh name="������������_GRAY_0" geometry={nodes['������������_GRAY_0'].geometry} material={materials.GRAY} />
                  <mesh name="������������_SNOW_0" geometry={nodes['������������_SNOW_0'].geometry} material={materials.SNOW} />
                </group>
                <group name="����������_1" position={[1012.386, 1880.761, 1174.948]} rotation={[1.304, -0.597, -1.8]}>
                  <mesh name="����������_1__0" geometry={nodes['����������_1__0'].geometry} material={materials.RootNode} />
                  <mesh name="����������_1_dark_0" geometry={nodes['����������_1_dark_0'].geometry} material={materials.dark} />
                </group>
                <group name="��������������" position={[-1459.663, 658.963, 194.04]}>
                  <group name="��������������_4" position={[5143.337, 1120.861, -1430.086]} rotation={[Math.PI / 2, 0, 0.721]}>
                    <mesh name="��������������_pnl_on_0" geometry={nodes['��������������_pnl_on_0'].geometry} material={materials.pnl_on} />
                  </group>
                  <group name="����������������_1_1" position={[5168.481, 151.114, -1458.708]} rotation={[0, -0.721, 0]}>
                    <mesh name="����������������_1_BLUE_LIGHT_0" geometry={nodes['����������������_1_BLUE_LIGHT_0'].geometry} material={materials.BLUE_LIGHT} />
                  </group>
                  <group name="������������_6" position={[-4552.422, 1185.743, -3348.578]} rotation={[Math.PI / 2, 0, -1.014]}>
                    <mesh name="������������__0_3" geometry={nodes['������������__0_3'].geometry} material={materials.RootNode} />
                  </group>
                  <group name="Cube" position={[-4524.266, 970.866, -3331.04]} rotation={[Math.PI / 2, 0, -1.014]}>
                    <mesh name="Cube__0" geometry={nodes.Cube__0.geometry} material={materials.RootNode} />
                    <mesh name="Cube_pnl_off_0" geometry={nodes.Cube_pnl_off_0.geometry} material={materials.pnl_off} />
                  </group>
                </group>
                <group name="����������_2" position={[-7619.343, -1068.053, 8337.102]} rotation={[-0.251, 1.231, 0.536]}>
                  <mesh name="����������_2__7" geometry={nodes['����������_2__7'].geometry} material={materials.RootNode} />
                  <mesh name="����������_2_ZABor_0" geometry={nodes['����������_2_ZABor_0'].geometry} material={materials.ZABor} />
                </group>
                <group name="����������_1_1" position={[6536.02, -669.901, 5530.106]} rotation={[-2.065, -1.027, -2.344]}>
                  <mesh name="����������_1__22" geometry={nodes['����������_1__22'].geometry} material={materials.RootNode} />
                  <mesh name="����������_1_ZABor_11" geometry={nodes['����������_1_ZABor_11'].geometry} material={materials.ZABor} />
                </group>
                <group name="������������_2" position={[3353.238, 512.944, 2838.802]} rotation={[Math.PI, -1.19, Math.PI]}>
                  <mesh name="������������_2__0" geometry={nodes['������������_2__0'].geometry} material={materials.RootNode} />
                </group>
                <group name="��������������_1" position={[-5824.53, -53.934, -4289.046]} rotation={[Math.PI, -0.866, Math.PI]}>
                  <mesh name="��������������__2" geometry={nodes['��������������__2'].geometry} material={materials.RootNode} />
                  <mesh name="��������������_transformat_2" geometry={nodes['��������������_transformat_2'].geometry} material={materials.transformat} />
                  <mesh name="��������������_RED_LIGHT_0" geometry={nodes['��������������_RED_LIGHT_0'].geometry} material={materials.RED_LIGHT} />
                </group>
                <group name="��������������_2" position={[-4256.812, -852.67, -7823.75]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="��������������_SNOW_0" geometry={nodes['��������������_SNOW_0'].geometry} material={materials.SNOW} />
                </group>
                <group name="������_����������������" position={[454.954, 1696.282, -1677.999]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh name="������_����������������_SNOW_0" geometry={nodes['������_����������������_SNOW_0'].geometry} material={materials.SNOW} />
                </group>
                <group name="������������_1" position={[9289.638, -179.538, 1817.652]} rotation={[-Math.PI, -0.801, -Math.PI]}>
                  <mesh name="������������__0" geometry={nodes['������������__0'].geometry} material={materials.RootNode} />
                </group>
                <group name="������������������" position={[-6923.719, -389.979, -496.864]} rotation={[Math.PI, 0, Math.PI]}>
                  <mesh name="������������������__0" geometry={nodes['������������������__0'].geometry} material={materials.RootNode} />
                  <mesh name="������������������_BLUE_LIGHT_0" geometry={nodes['������������������_BLUE_LIGHT_0'].geometry} material={materials.BLUE_LIGHT} />
                </group>
                <group name="��������������_2_1" position={[735.161, 1499.553, -1147.442]} rotation={[Math.PI, 0, -Math.PI]}>
                  <mesh name="��������������_2__0" geometry={nodes['��������������_2__0'].geometry} material={materials.RootNode} />
                  <mesh name="��������������_2_SNOW_0" geometry={nodes['��������������_2_SNOW_0'].geometry} material={materials.SNOW} />
                  <mesh name="��������������_2_DARK_0" geometry={nodes['��������������_2_DARK_0'].geometry} material={materials.DARK} />
                  <mesh name="��������������_2_RED_LIGHT_0" geometry={nodes['��������������_2_RED_LIGHT_0'].geometry} material={materials.RED_LIGHT} />
                </group>
                <group name="����������������_����������" position={[1145.585, -563.143, 6751.844]}>
                  <mesh name="����������������_����������__0" geometry={nodes['����������������_����������__0'].geometry} material={materials.RootNode} />
                </group>
                <group name="��������������������">
                  <mesh name="��������������������_PROVODA_0" geometry={nodes['��������������������_PROVODA_0'].geometry} material={materials.PROVODA} />
                </group>
                <group name="Cube_1" position={[56.115, 1966.436, 2322.133]} rotation={[Math.PI, 0, -Math.PI]}>
                  <mesh name="Cube_1__4" geometry={nodes.Cube_1__4.geometry} material={materials.RootNode} />
                  <mesh name="Cube_1_RED_4" geometry={nodes.Cube_1_RED_4.geometry} material={materials.material} />
                  <mesh name="Cube_1_screen_4" geometry={nodes.Cube_1_screen_4.geometry} material={materials.screen} />
                  <mesh name="Cube_1_dark_1" geometry={nodes.Cube_1_dark_1.geometry} material={materials.dark} />
                </group>
                <group name="������������_3" position={[3685.34, -278.331, 6266.633]}>
                  <mesh name="������������__0_1" geometry={nodes['������������__0_1'].geometry} material={materials.RootNode} />
                  <mesh name="������������_GRAY_0_1" geometry={nodes['������������_GRAY_0_1'].geometry} material={materials.GRAY} />
                </group>
                <group name="����������_1_2" position={[1172.597, 87.506, 46.746]}>
                  <mesh name="����������_1_kust_0" geometry={nodes['����������_1_kust_0'].geometry} material={materials.kust} />
                </group>
                <group name="��������������_1_1">
                  <mesh name="��������������_1_DARK_0" geometry={nodes['��������������_1_DARK_0'].geometry} material={materials.DARK} />
                </group>
                <group name="Cube_4" position={[806.037, 1508.563, -1104.822]} rotation={[Math.PI / 2, 0, -Math.PI]}>
                  <mesh name="Cube_4__0" geometry={nodes.Cube_4__0.geometry} material={materials.RootNode} />
                </group>
                <group name="Cube_49_Instance" position={[-8633.865, -419.182, -4260.491]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh name="Cube_49_Instance__0" geometry={nodes.Cube_49_Instance__0.geometry} material={materials.RootNode} />
                </group>
                <group name="Cube_2" position={[-8149.819, -23.39, -807.621]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                  <mesh name="Cube_2__0" geometry={nodes.Cube_2__0.geometry} material={materials.RootNode} />
                  <mesh name="Cube_2_SNOW_0" geometry={nodes.Cube_2_SNOW_0.geometry} material={materials.SNOW} />
                </group>
                <group name="Sweep_1" position={[-5932.867, 78.091, 0]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh name="Sweep_1__0" geometry={nodes.Sweep_1__0.geometry} material={materials.RootNode} />
                  <mesh name="Sweep_1_SNOW_0" geometry={nodes.Sweep_1_SNOW_0.geometry} material={materials.SNOW} />
                </group>
                <group name="������������_1_1">
                  <mesh name="������������_1_dark_0" geometry={nodes['������������_1_dark_0'].geometry} material={materials.dark} />
                </group>
                <group name="����������_1_3" position={[0, -487.885, -4864.002]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh name="����������_1__0_1" geometry={nodes['����������_1__0_1'].geometry} material={materials.RootNode} />
                  <mesh name="����������_1_GREEN_0" geometry={nodes['����������_1_GREEN_0'].geometry} material={materials.GREEN} />
                </group>
                <group name="Cube_3" position={[3855.703, 2050.816, -1279.481]} rotation={[Math.PI / 2, 0, -0.901]}>
                  <mesh name="Cube_3_RED_LIGHT_0" geometry={nodes.Cube_3_RED_LIGHT_0.geometry} material={materials.RED_LIGHT} />
                </group>
                <group name="Cloner_2" position={[3014.713, -690.922, 7355.072]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                  <mesh name="Cloner_2_dark_0" geometry={nodes.Cloner_2_dark_0.geometry} material={materials.dark} />
                  <mesh name="Cloner_2_SNOW_0" geometry={nodes.Cloner_2_SNOW_0.geometry} material={materials.SNOW} />
                  <mesh name="Cloner_2__0" geometry={nodes.Cloner_2__0.geometry} material={materials.RootNode} />
                </group>
                <group name="��������������_1_2" position={[4508.432, 303.902, -2653.478]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="��������������_1__0" geometry={nodes['��������������_1__0'].geometry} material={materials.RootNode} />
                </group>
                <group name="��������������������_1" position={[3754.787, 45.934, 1122.899]} rotation={[-Math.PI, -1.187, -Math.PI]}>
                  <mesh name="��������������������__0" geometry={nodes['��������������������__0'].geometry} material={materials.RootNode} />
                </group>
                <group name="Cone_1" position={[7303.381, 1687.231, 346.901]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="Cone_1__0" geometry={nodes.Cone_1__0.geometry} material={materials.RootNode} />
                </group>
                <group name="������������_4" position={[-1260.474, -164.724, 7074.089]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="������������__0_2" geometry={nodes['������������__0_2'].geometry} material={materials.RootNode} />
                </group>
                <group name="��������������_3" position={[1273.282, 256.515, 645.283]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="��������������_DARK_0" geometry={nodes['��������������_DARK_0'].geometry} material={materials.DARK} />
                  <mesh name="��������������_SNOW_0_1" geometry={nodes['��������������_SNOW_0_1'].geometry} material={materials.SNOW} />
                </group>
                <group name="___" position={[-96.618, 1573.647, 2785.437]}>
                  <mesh name="_____0" geometry={nodes._____0.geometry} material={materials.RootNode} />
                </group>
                <group name="Plane_1" position={[2.704, 986.251, -4063.043]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                  <mesh name="Plane_1__0" geometry={nodes.Plane_1__0.geometry} material={materials.RootNode} />
                  <mesh name="Plane_1_WHITE_0" geometry={nodes.Plane_1_WHITE_0.geometry} material={materials.WHITE} />
                </group>
                <group name="��_����������_1" position={[6900.77, 555.429, 1846.056]}>
                  <mesh name="��_����������_1__0" geometry={nodes['��_����������_1__0'].geometry} material={materials.RootNode} />
                </group>
                <group name="Cloner" position={[1102.911, 261.197, -998.964]}>
                  <mesh name="Cloner_Brevna_0" geometry={nodes.Cloner_Brevna_0.geometry} material={materials.Brevna} />
                </group>
                <group name="����������������_1" position={[-3858.451, 346.232, 2266.945]} rotation={[0, -Math.PI / 2, 0]}>
                  <mesh name="����������������_dark_0" geometry={nodes['����������������_dark_0'].geometry} material={materials.dark} />
                  <mesh name="����������������_SNOW_1" geometry={nodes['����������������_SNOW_1'].geometry} material={materials.SNOW} />
                </group>
                <group name="������������_5" position={[-858.352, 4805.24, 657.659]}>
                  <group name="������������_2_1" position={[-1753.326, -4371.564, 1116.08]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="������������_2_HERNIA_0" geometry={nodes['������������_2_HERNIA_0'].geometry} material={materials.HERNIA} />
                    <mesh name="������������_2_SNOW_0" geometry={nodes['������������_2_SNOW_0'].geometry} material={materials.SNOW} />
                    <mesh name="������������_2__0_1" geometry={nodes['������������_2__0_1'].geometry} material={materials.RootNode} />
                    <mesh name="������������_2_RED_LIGHT_0" geometry={nodes['������������_2_RED_LIGHT_0'].geometry} material={materials.RED_LIGHT} />
                  </group>
                  <group name="����������_1_4" position={[1169.013, -5159.833, -207.705]}>
                    <mesh name="����������_1__0_2" geometry={nodes['����������_1__0_2'].geometry} material={materials.RootNode} />
                    <mesh name="����������_1_TROS_0" geometry={nodes['����������_1_TROS_0'].geometry} material={materials.TROS} />
                  </group>
                  <group name="Cylinder_3" position={[-2111.524, -4823.309, -1193.67]} rotation={[Math.PI / 2, 0, Math.PI]}>
                    <mesh name="Cylinder_3_dark_0" geometry={nodes.Cylinder_3_dark_0.geometry} material={materials.dark} />
                    <mesh name="Cylinder_3_SNOW_0" geometry={nodes.Cylinder_3_SNOW_0.geometry} material={materials.SNOW} />
                  </group>
                  <group name="herniio" position={[2890.17, -4805.24, -657.659]}>
                    <mesh name="herniio__0" geometry={nodes.herniio__0.geometry} material={materials.RootNode} />
                  </group>
                  <group name="����������_2_1" position={[-80.517, -1255.21, 92.558]}>
                    <mesh name="����������_2_BLUE_LIGHT2_0" geometry={nodes['����������_2_BLUE_LIGHT2_0'].geometry} material={materials.BLUE_LIGHT2} />
                  </group>
                  <group name="����������" position={[1334.808, 1282.8, 534.006]}>
                    <mesh name="����������_BLUE_LIGHT_0" geometry={nodes['����������_BLUE_LIGHT_0'].geometry} material={materials.BLUE_LIGHT} />
                  </group>
                  <group name="������������������_1" position={[539.897, -5375.668, -657.659]}>
                    <mesh name="������������������_1_dark_0" geometry={nodes['������������������_1_dark_0'].geometry} material={materials.dark} />
                    <mesh name="������������������_1_SNOW_0" geometry={nodes['������������������_1_SNOW_0'].geometry} material={materials.SNOW} />
                  </group>
                </group>
                <group name="������" position={[889.965, 637.208, 113.974]}>
                  <group name="����������_3" position={[-966.943, 1461.43, 133.171]}>
                    <mesh name="����������_GREEN_0" geometry={nodes['����������_GREEN_0'].geometry} material={materials.GREEN} />
                  </group>
                  <group name="��������������_5" position={[-118.037, 1232.227, 1098.181]} rotation={[-0.136, 0.189, 0.123]}>
                    <group name="��������_��������������" position={[208.509, 780.833, 0]}>
                      <mesh name="��������_��������������_YELLOW_1" geometry={nodes['��������_��������������_YELLOW_1'].geometry} material={materials.YELLOW} />
                      <mesh name="��������_��������������_RED_1" geometry={nodes['��������_��������������_RED_1'].geometry} material={materials.RED_0} />
                    </group>
                    <group name="Extrude_1" position={[-771.928, -1869.436, -1212.154]}>
                      <mesh name="Extrude_1_GREEN_4" geometry={nodes.Extrude_1_GREEN_4.geometry} material={materials.GREEN} />
                      <mesh name="Extrude_1_WHITE_4" geometry={nodes.Extrude_1_WHITE_4.geometry} material={materials.WHITE} />
                      <mesh name="Extrude_1_YELLOW_JUST_4" geometry={nodes.Extrude_1_YELLOW_JUST_4.geometry} material={materials.YELLOW_JUST} />
                      <mesh name="Extrude_1_YELLOW_3" geometry={nodes.Extrude_1_YELLOW_3.geometry} material={materials.YELLOW} />
                    </group>
                    <group name="Cube_1_2" position={[-1.013, 1353.088, -8.765]} rotation={[0, -Math.PI / 2, 0]}>
                      <mesh name="Cube_1_2_WHITE_0" geometry={nodes.Cube_1_2_WHITE_0.geometry} material={materials.WHITE} />
                    </group>
                  </group>
                  <group name="������������_1_2" position={[186.772, 603.167, 1191.857]} rotation={[Math.PI, -Math.PI / 2, 0]}>
                    <mesh name="������������_1_glass_0" geometry={nodes['������������_1_glass_0'].geometry} material={materials.glass} />
                  </group>
                  <group name="��������������_6" position={[219.079, 501.951, 569.452]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                    <mesh name="��������������_RED_0" geometry={nodes['��������������_RED_0'].geometry} material={materials.RED_0} />
                  </group>
                  <group name="����������_4" position={[-276.881, 322.34, 849.948]}>
                    <mesh name="����������_WHITE_0" geometry={nodes['����������_WHITE_0'].geometry} material={materials.WHITE} />
                  </group>
                  <group name="����������������_3" position={[763.461, 604.443, 59.64]} rotation={[Math.PI, -1.571, 0]}>
                    <mesh name="����������������_YELLOW_0" geometry={nodes['����������������_YELLOW_0'].geometry} material={materials.YELLOW} />
                  </group>
                  <group name="��������_��������" position={[-889.965, -559.709, -68.886]}>
                    <mesh name="��������_��������_WHITE_0" geometry={nodes['��������_��������_WHITE_0'].geometry} material={materials.WHITE} />
                  </group>
                  <group name="Cube_1_3" position={[-1292.999, -318.056, -1787.911]} rotation={[0, Math.PI / 2, 0]}>
                    <mesh name="Cube_1_3_RED_0" geometry={nodes.Cube_1_3_RED_0.geometry} material={materials.RED_0} />
                    <mesh name="Cube_1_3_YELLOW_JUST_0" geometry={nodes.Cube_1_3_YELLOW_JUST_0.geometry} material={materials.YELLOW_JUST} />
                    <mesh name="Cube_1_3_WHITE_0" geometry={nodes.Cube_1_3_WHITE_0.geometry} material={materials.WHITE} />
                  </group>
                  <group name="��������������_7" position={[-501.382, -481.326, -2154.555]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="��������������_SNOW_0_2" geometry={nodes['��������������_SNOW_0_2'].geometry} material={materials.SNOW} />
                    <mesh name="��������������_FUNDAMENT_0" geometry={nodes['��������������_FUNDAMENT_0'].geometry} material={materials.FUNDAMENT} />
                  </group>
                  <group name="������������_7" position={[-994.002, 1160.156, 2144.287]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="������������_RED_0" geometry={nodes['������������_RED_0'].geometry} material={materials.RED_0} />
                  </group>
                  <group name="����������_Instance" position={[-986.99, 2023.35, -437.605]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="����������_Instance__0" geometry={nodes['����������_Instance__0'].geometry} material={materials.RootNode} />
                  </group>
                  <group name="������������������_1_1" position={[-889.965, 1859.325, 2400.594]}>
                    <mesh name="������������������_1_YELLOW_JUST_0" geometry={nodes['������������������_1_YELLOW_JUST_0'].geometry} material={materials.YELLOW_JUST} />
                    <mesh name="������������������_1_RED_0" geometry={nodes['������������������_1_RED_0'].geometry} material={materials.RED_0} />
                    <mesh name="������������������_1_WHITE_0" geometry={nodes['������������������_1_WHITE_0'].geometry} material={materials.WHITE} />
                  </group>
                  <group name="����������������������_����������_1" position={[-2217.521, 1475.672, 211.471]} rotation={[2.16, 0, 0]}>
                    <mesh name="����������������������_����������_1_YELLOW_0" geometry={nodes['����������������������_����������_1_YELLOW_0'].geometry} material={materials.YELLOW} />
                  </group>
                  <group name="����������_����������" position={[-77.618, 1366.359, 1095.578]} rotation={[0, -Math.PI / 2, 0]}>
                    <mesh name="����������_����������_dark_0" geometry={nodes['����������_����������_dark_0'].geometry} material={materials.dark} />
                  </group>
                  <group name="������_������" position={[547.602, -496.539, -152.205]}>
                    <mesh name="������_������_FUNDAMENT_3" geometry={nodes['������_������_FUNDAMENT_3'].geometry} material={materials.FUNDAMENT} />
                    <mesh name="������_������_YELLOW_2" geometry={nodes['������_������_YELLOW_2'].geometry} material={materials.YELLOW} />
                  </group>
                </group>
                <group name="����������������_2" position={[-83.842, -254.392, 1356.409]}>
                  <group name="Maple_tree" position={[-2424.848, -232.158, 2183.863]}>
                    <group name="Forester_Tree">
                      <mesh name="Forester_Tree_DARK_0" geometry={nodes.Forester_Tree_DARK_0.geometry} material={materials.DARK} />
                    </group>
                  </group>
                  <group name="��������������_8" position={[8985.247, -1.781, 494.722]}>
                    <mesh name="��������������_SNOW_0_3" geometry={nodes['��������������_SNOW_0_3'].geometry} material={materials.SNOW} />
                  </group>
                  <group name="������������_8" position={[83.842, 230.474, -1356.409]}>
                    <mesh name="������������_DISPL_0" geometry={nodes['������������_DISPL_0'].geometry} material={materials.DISPL} />
                  </group>
                  <group name="����������_5" position={[83.842, -175.638, -1356.409]}>
                    <mesh name="����������_flat_0" geometry={nodes['����������_flat_0'].geometry} material={materials.flat} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Terem;
