/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

import toriiScene from "../assets/3d/torii.glb";

export function Torii(props) {
  const { nodes, materials } = useGLTF(toriiScene);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat23} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat14}
      />
    </group>
  );
}


